### ISSUE TITLE
Add support to inline base64 images in css/json/js

### ISSUE THREAD

**Issue by doochik** [borschik/borschik#9]
For example

`.borschik` config. There is no path-mapping, so we need to declare path and maybe wildcard for inlined files (max size?)

``` json
{
  "inline_base64": {
    "static/icon": "*.svg"
  }
}
```

Input CSS

``` css
.a {
  background: url('static/icon/ico.svg')
}
```

Ouput CSS

``` css
.a {
  background: url(data:image/svg+xml;base64,...)
}
```
